/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 0;
extern const char* const kSvnInfo[0] = {};
extern const char kBuildType[] = "release";
extern const char kBuildTime[] = "Mon Oct 13 14:50:05 2014";
extern const char kBuilderName[] = "yye";
extern const char kHostName[] = "yye-QCRI";
extern const char kCompiler[] = "GCC 4.8.2-19ubuntu1)";
}}
