/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 1;
extern const char* const kSvnInfo[1] = {"commit c4e5be4175c4ddc740eae46530adddf690d3b8d6\n\
Author: yye <yeyin.tsinghua@gmail.com>\n\
Date:   Mon Oct 13 19:04:04 2014 +0300\n\
\n\
    add .gitignore\n\
"};
extern const char kBuildType[] = "release";
extern const char kBuildTime[] = "Mon Oct 13 19:17:34 2014";
extern const char kBuilderName[] = "yye";
extern const char kHostName[] = "yye-QCRI";
extern const char kCompiler[] = "GCC 4.8.2-19ubuntu1)";
}}
